name: AI News Monitor

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  monitor-news:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create directories
      run: |
        mkdir -p ./config ./data ./logs

    - name: Create API secrets file
      run: |
        echo '${{ secrets.API_SECRETS_JSON }}' > ./config/api_secrets.json

    - name: Download previous sent news
      uses: actions/download-artifact@v4
      with:
        name: sent-news-data
        path: ./data/
      continue-on-error: true

    - name: Ensure sent_news.json exists
      run: |
        mkdir -p ./data
        if [ ! -f ./data/sent_news.json ]; then
          echo "Creating initial sent_news.json"
          echo '[]' > ./data/sent_news.json
        fi
        echo "File contents:"
        cat ./data/sent_news.json

    - name: Run AI News Monitor
      run: |
        python ai_news_monitor.py
        if [ ! -f ./data/sent_news.json ]; then
          echo '[]' > ./data/sent_news.json
        fi
      env:
        PYTHONIOENCODING: utf-8
        TZ: Europe/Kiev

    - name: Upload sent news data
      uses: actions/upload-artifact@v4
      with:
        name: sent-news-data
        path: ./data/sent_news.json
        if-no-files-found: warn
        overwrite: true
        retention-days: 90

    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: logs-${{ github.run_number }}
        path: ./logs/
        retention-days: 30